jobs:
  include:
    - os: linux
      name: android
      if: branch = master
      dist: bionic
      language: java
      jdk: openjdk8
      env:
        - ANDROID_SDK_TOOLS=commandlinetools-linux-6200805_latest.zip
      before_install:
        - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
        - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
        - export PATH=$PATH:$HOME/sdk/tools/bin
        - export ANDROID_HOME=$HOME/sdk
        - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
        - yes | sdkmanager --licenses --sdk_root="${ANDROID_HOME}"
        - sdkmanager --install "emulator" "tools" "platform-tools" --sdk_root="${ANDROID_HOME}"
        - sdkmanager --list --sdk_root="${ANDROID_HOME}" | head -15
        - sdkmanager --install "build-tools;25.0.2" "platforms;android-25" --sdk_root="${ANDROID_HOME}"
        - sdkmanager --install "system-images;android-25;default;x86" --sdk_root="${ANDROID_HOME}"
        - sdkmanager --list --sdk_root="${ANDROID_HOME}" | head -15
        - echo no | avdmanager create avd --force -n test -k "system-images;android-25;default;x86"
        - git clone https://github.com/flutter/flutter.git -b beta --depth 1
        - export PATH=$PATH:$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$ANDROID_HOME/build-tools/28.0.3/
        - flutter doctor
      script:
        - cd example/
        - flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        - flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        - flutter emulator --create
        - flutter emulator --launch test
        - flutter drive
    - os: osx
      name: apple
      if: branch = master
      osx_image: xcode11.5
      xcode_workspace: TravisCIBlog.xcworkspace
      xcode_scheme: TravisCIBlog
      xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X
      addons:
        homebrew:
          packages:
            - usbmuxd
            - libimobiledevice
            - ideviceinstaller
            - ios-deploy
            - libffi
      before_install:
        - brew unlink usbmuxd
        - brew link usbmuxd
        - git clone https://github.com/flutter/flutter.git -b stable --depth 1
        - sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        # - flutter/bin/flutter emulators -h
      script:
        - cd example/
        - ../flutter/bin/flutter build ios --debug --no-codesign
        - ls build/ios/iphoneos/
        - mv build/ios/iphoneos/Runner.app ./Runner.app
        - mkdir Payload && cd Payload
        - ln -s ../Runner.app
        - cd ..
        - zip -r app.ipa Payload
      deploy:
        provider: releases
        api_key: "$GITHUB_OAUTH"
        file:
          - app.ipa
        skip_cleanup: true
        on:
          branch: master